version: '3'
services:
  core:
    build: ./verify-core
    ports:
    - "8001:8000"
    volumes:
    - .:/code/verify-core
    - logvolume01:/var/log
    links:
    - block
  block:
    build: ./verify-block
    ports:
    - "8000:8000"
    volumes:
    - .:/code/verify-block
    - logvolume01:/var/log
  block-frontend:
    build: ./verify-block/frontend
    ports:
    - "8081:80"
    volumes:
    - .:/code/verify-block/frontend
    - logvolume01:/var/log/nginx
    links:
    - block
volumes:
  logvolume01: {}
