version: '3'
services:
  core:
    build: ./verify-core
    ports:
    - "8001:8000"
    volumes:
    - .:/code/verify-core
    - logvolume01:/var/log
    links:
    - block
    command: sh -c "python manage.py loaddata homer && uwsgi --show-config"
  block:
    build: ./verify-block
    ports:
    - "8000:8000"
    volumes:
    - .:/code/verify-block
    - logvolume01:/var/log
  block-frontend:
    build: ./verify-block/frontend
    ports:
    - "80:8080"
    volumes:
    - .:/code/verify-block/frontend
    - logvolume01:/var/log/nginx
    links:
    - block
volumes:
  logvolume01: {}
