version: '3'
services:
  core:
    build: ./verify-core
    ports:
    - "8001:8000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - block
  block:
    build: ./verify-block
    ports:
    - "8000:8000"
    volumes:
    - .:/code
    - logvolume01:/var/log
  block-frontend:
    build: ./verify-block/frontend
    ports:
    - "3000:3000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - block
volumes:
  logvolume01: {}